services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: simpleAPI
            POSTGRES_PASSWORD: password
    app:
        image: node:12-alpine
        command: sh -c "yarn install && yarn run seed-database && yarn run nodemon"
        ports:
            - 3000:3000
            - 9229:9229
        working_dir: /app
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules/
        environment:
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASSWORD=password
            - DB_NAME=postgres
            - DB_SCHEMA=./schema.sql
            - APP_HOST=0.0.0.0

volumes:
    node_modules: